import 'server-only';
import { prisma } from './prisma';
import type { Prisma } from '@prisma/client';

// =============================================================================
// KAIA-4263 / KAIA-8107 — Canonical onboarding activation.
//
// When the Stripe webhook (KAIA-4262) confirms the first payment for a
// self-serve onboarding session, the rows generated by the wizard
// (Tenant stub, ChatbotClient stub, ClientProduct stub) must converge
// into the canonical multi-tenant schema:
//
//   * Tenant.slug    ← OnboardingSession.tenant_slug
//   * User(email)    ← OnboardingSession.email
//   * Profile        ← User + TenantId, role='owner'
//   * ChatbotClient  ← OnboardingSession.email + tenantId, state='live'
//   * ChatbotClientUser ← nextAuthEmail = email, links User + ChatbotClient
//   * ClientProduct  ← status='active', tenantId, clientId, productId
//   * OnboardingSession.status = 'active' + activationAt
//
// All seven writes run inside a single Prisma transaction so the
// activation either fully commits or rolls back. Webhook redelivery
// (Stripe retries failed events for up to 3 days) is the realistic
// duplicate path: re-running the function must be a no-op that
// re-returns the canonical resolved rows.
//
// Idempotency contract:
//
//   * The function is a pure upsert on the canonical keys
//     (Tenant.slug, User.email, Profile.userId, ChatbotClient.email,
//     ChatbotClientUser.nextAuthEmail, ClientProduct.(clientId,productId)).
//   * OnboardingSession.status is set to 'active' only if not already
//     'active'. Each retry gets a fresh activationAt written only on
//     the first transition — subsequent calls are no-ops on that row.
//   * The Stripe webhook event-id idempotency table
//     (StripeWebhookEvent) is the outer guard — if it short-circuits
//     the handler at the top, this function never runs. The inner
//     idempotency here is defence-in-depth for race conditions and
//     manual operator replays.
// =============================================================================

export interface ActivateOnboardingInput {
  // The wizard session token. Required — it's the join key from the
  // Stripe Checkout metadata (`kairikos_onboarding_session`).
  sessionToken: string;
  // The Stripe customer id resolved by the webhook handler. Optional
  // because the canonical creation flow can also be triggered through
  // /api/internal/onboarding/activate (operator backfill) without a
  // Stripe customer.
  stripeCustomerId?: string | null;
  // Stripe subscription id from the webhook payload. Stored on the
  // Subscription row's stripe_id (existing KAIA-4262 contract).
  stripeSubscriptionId?: string | null;
  // Stripe price id from the webhook payload. Used to resolve the
  // Product tier when the OnboardingSession did not record one.
  stripePriceId?: string | null;
  // Optional override for the activation timestamp. Defaults to NOW().
  activatedAt?: Date;
}

export interface ActivateOnboardingResult {
  activated: boolean;
  alreadyActive: boolean;
  tenantId: string;
  clientId: string;
  userId: string;
  clientProductId: string;
  activationAt: Date;
}

export class OnboardingActivationError extends Error {
  constructor(
    message: string,
    public readonly code:
      | 'session_not_found'
      | 'product_tier_missing'
      | 'product_not_found'
      | 'stripe_customer_mismatch',
  ) {
    super(message);
    this.name = 'OnboardingActivationError';
  }
}

/**
 * Atomic, idempotent activation of an OnboardingSession into the
 * canonical multi-tenant schema.
 *
 * Steps (all inside a single `prisma.$transaction`):
 *
 *  1. Resolve OnboardingSession by sessionToken. Fail if missing.
 *  2. If status === 'active' already, look up the canonical rows via
 *     the cached tenantId/clientId columns and return
 *     `{ alreadyActive: true }`. No writes.
 *  3. Resolve the Product row by tier (or by stripePriceId when tier
 *     is missing). Fail if neither resolves.
 *  4. Find-or-create Tenant by slug.
 *  5. If stripeCustomerId is provided, validate it matches the existing
 *     Tenant.stripeCustomerId (or set it). Fail on mismatch (defends
 *     against a session_token being reused with a different Stripe
 *     customer).
 *  6. Find-or-create User by email.
 *  7. Find-or-create Profile (userId, tenantId, role='owner').
 *  8. Find-or-create ChatbotClient (email, tenantId). Set state='live'.
 *  9. Find-or-create ChatbotClientUser (clientId, nextAuthEmail,
 *     userId, tenantId).
 * 10. Find-or-create ClientProduct (clientId, productId, status='active').
 * 11. Set OnboardingSession.status='active', activationAt, tenantId,
 *     clientId, clientProductId.
 * 12. Return the canonical row ids.
 */
export async function activateOnboardingSession(
  input: ActivateOnboardingInput,
): Promise<ActivateOnboardingResult> {
  if (!prisma) {
    throw new OnboardingActivationError(
      'prisma client unavailable',
      'session_not_found',
    );
  }
  return prisma.$transaction(async (tx) => {
    const session = await tx.onboardingSession.findUnique({
      where: { sessionToken: input.sessionToken },
      select: {
        id: true,
        sessionToken: true,
        email: true,
        tenantSlug: true,
        productTier: true,
        productId: true,
        clientProductId: true,
        tenantId: true,
        clientId: true,
        status: true,
        activationAt: true,
        businessName: true,
      },
    });
    if (!session) {
      throw new OnboardingActivationError(
        `onboarding_session not found: ${input.sessionToken}`,
        'session_not_found',
      );
    }

    // Idempotency check: if already active, return the canonical rows.
    if (session.status === 'active' && session.tenantId && session.clientId && session.clientProductId) {
      const existing = await tx.clientProduct.findUnique({
        where: { id: session.clientProductId },
        select: { id: true, clientId: true, tenantId: true },
      });
      if (existing) {
        const user = await tx.user.findUnique({
          where: { email: session.email },
          select: { id: true },
        });
        if (user) {
          return {
            activated: true,
            alreadyActive: true,
            tenantId: existing.tenantId ?? session.tenantId,
            clientId: existing.clientId,
            userId: user.id,
            clientProductId: existing.id,
            activationAt: session.activationAt ?? new Date(),
          };
        }
      }
    }

    // Resolve the Product row. Prefer the explicit productId on the
    // session (the wizard set it at checkout-time). Otherwise fall back
    // to the tier, then to the Stripe price id.
    let product: { id: string; tier: string } | null = null;
    if (session.productId) {
      product = await tx.product.findUnique({
        where: { id: session.productId },
        select: { id: true, tier: true },
      });
    }
    if (!product && session.productTier) {
      product = await tx.product.findUnique({
        where: { tier: session.productTier },
        select: { id: true, tier: true },
      });
    }
    if (!product && input.stripePriceId) {
      product = await tx.product.findUnique({
        where: { stripePriceId: input.stripePriceId },
        select: { id: true, tier: true },
      });
    }
    if (!product) {
      throw new OnboardingActivationError(
        `cannot resolve product for session ${session.id}: tier=${session.productTier} stripe_price=${input.stripePriceId ?? 'n/a'}`,
        'product_not_found',
      );
    }

    // 4. Find-or-create Tenant by slug.
    const tenant = await tx.tenant.upsert({
      where: { slug: session.tenantSlug },
      create: {
        slug: session.tenantSlug,
        name: session.businessName ?? session.tenantSlug,
        status: 'active',
      },
      update: {},
      select: { id: true, stripeCustomerId: true },
    });

    // 5. Set Tenant.stripeCustomerId if the webhook provided one and
    // the tenant doesn't already have one. Allow the existing value
    // to win — a different stripe customer on the same tenant would
    // indicate a session_token collision and is rejected.
    if (input.stripeCustomerId) {
      if (tenant.stripeCustomerId && tenant.stripeCustomerId !== input.stripeCustomerId) {
        throw new OnboardingActivationError(
          `tenant ${tenant.id} already linked to customer ${tenant.stripeCustomerId}, refusing to overwrite with ${input.stripeCustomerId}`,
          'stripe_customer_mismatch',
        );
      }
      if (!tenant.stripeCustomerId) {
        await tx.tenant.update({
          where: { id: tenant.id },
          data: { stripeCustomerId: input.stripeCustomerId },
        });
      }
    }

    // 6. Find-or-create User by email.
    const email = session.email.trim().toLowerCase();
    const user = await tx.user.upsert({
      where: { email },
      create: {
        email,
        role: 'client',
        passwordHash: '__must_reset__',
      },
      update: {},
      select: { id: true },
    });

    // 7. Find-or-create Profile.
    await tx.profile.upsert({
      where: { userId: user.id },
      create: {
        userId: user.id,
        tenantId: tenant.id,
        role: 'owner',
      },
      update: {
        tenantId: tenant.id,
        role: 'owner',
      },
    });

    // 8. Find-or-create ChatbotClient.
    const client = await tx.chatbotClient.upsert({
      where: { email },
      create: {
        email,
        name: session.businessName ?? email,
        companyName: session.businessName ?? null,
        tier: product.tier,
        state: 'live',
        tenantId: tenant.id,
      },
      update: {
        state: 'live',
        tenantId: tenant.id,
        tier: product.tier,
        companyName: session.businessName ?? null,
      },
      select: { id: true },
    });

    // 9. Find-or-create ChatbotClientUser.
    await tx.chatbotClientUser.upsert({
      where: { nextAuthEmail: email },
      create: {
        clientId: client.id,
        nextAuthEmail: email,
        userId: user.id,
        tenantId: tenant.id,
      },
      update: {
        clientId: client.id,
        userId: user.id,
        tenantId: tenant.id,
      },
    });

    // 10. Find-or-create ClientProduct — UNIQUE on (clientId, productId).
    const clientProduct = await tx.clientProduct.upsert({
      where: { clientId_productId: { clientId: client.id, productId: product.id } },
      create: {
        clientId: client.id,
        productId: product.id,
        tenantId: tenant.id,
        status: 'active',
        createdBy: 'onboarding_activation',
        changedBy: 'onboarding_activation',
      },
      update: {
        status: 'active',
        tenantId: tenant.id,
        changedBy: 'onboarding_activation',
      },
      select: { id: true },
    });

    // 11. Mark OnboardingSession active. We only set activationAt on
    // the first transition so audit logs stay stable across retries.
    const activatedAt = input.activatedAt ?? new Date();
    const updatedSession = await tx.onboardingSession.update({
      where: { sessionToken: session.sessionToken },
      data: {
        status: 'active',
        activationAt: session.activationAt ?? activatedAt,
        tenantId: tenant.id,
        clientId: client.id,
        clientProductId: clientProduct.id,
        productId: product.id,
        productTier: product.tier,
        ...(input.stripeCustomerId ? { stripeCustomerId: input.stripeCustomerId } : {}),
      },
      select: { activationAt: true },
    });

    return {
      activated: true,
      alreadyActive: false,
      tenantId: tenant.id,
      clientId: client.id,
      userId: user.id,
      clientProductId: clientProduct.id,
      activationAt: updatedSession.activationAt ?? activatedAt,
    };
  });
}

/**
 * Look up the canonical activation state for an OnboardingSession
 * without mutating anything. Used by the React wizard's `/activate`
 * confirmation path and by the operator tooling to answer "is this
 * session active in the canonical schema yet?".
 */
export async function getOnboardingActivationState(
  sessionToken: string,
): Promise<{
  status: 'pending' | 'checkout_pending' | 'active' | 'abandoned';
  tenantId: string | null;
  clientId: string | null;
  clientProductId: string | null;
  userId: string | null;
  activationAt: Date | null;
} | null> {
  if (!prisma) return null;
  const session = await prisma.onboardingSession.findUnique({
    where: { sessionToken },
    select: {
      status: true,
      tenantId: true,
      clientId: true,
      clientProductId: true,
      activationAt: true,
      email: true,
    },
  });
  if (!session) return null;
  let userId: string | null = null;
  if (session.email) {
    const user = await prisma.user.findUnique({
      where: { email: session.email.trim().toLowerCase() },
      select: { id: true },
    });
    userId = user?.id ?? null;
  }
  return {
    status: session.status as 'pending' | 'checkout_pending' | 'active' | 'abandoned',
    tenantId: session.tenantId,
    clientId: session.clientId,
    clientProductId: session.clientProductId,
    userId,
    activationAt: session.activationAt,
  };
}

/**
 * Re-export the Prisma types so the Stripe webhook dispatcher can type
 * the return value without importing the full Prisma client.
 */
export type OnboardingActivationTx = Prisma.TransactionClient;
